[package]
name = "thetos_rc_demo"
version = "0.1.0"
edition = "2021"

# External consumer of ThetOS.
[dependencies]
thetos_entry  = { git = "https://github.com/rullo24/ThetOS", tag = "v1.1.0" }
nucleo_l152re = { git = "https://github.com/rullo24/ThetOS", tag = "v1.1.0" }

# ThetOS panic handlers must not unwind
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
